"""
step8/pr_creator.py — GitHub Pull Request Creator

HOW IT WORKS:
─────────────
Creates a pull request on the target repository with the auto-fix changes.

Flow:
    1. Authenticate via GitHub App
    2. Get the default branch (main/master)
    3. Create a new branch: fix/<failure-type>-<event-id-suffix>
    4. Apply code changes from the plan (create/modify files)
    5. Create the PR with a descriptive title and body
    6. Return PR metadata (url, branch, status)

PR BODY INCLUDES:
    - What failed (triage summary)
    - What was fixed (plan description)
    - What files were changed
    - Confidence level
    - Link to the failed workflow run
    - ⚠️ "This PR was auto-generated by RepoMind" badge

SAFETY:
    - Creates a BRANCH, not direct push to main
    - Human review still required (PR must be merged manually)
    - PR body contains all context for the reviewer

COMMUNICATION:
─────────────
Worker calls: PRCreator().create_pr(repo, triage, plan, event_id, head_branch)
Returns: { url, branch, commit_sha, title, status }
Stored in artifacts.json → "pr" section
"""

from typing import Dict, Any, Optional
from datetime import datetime, timezone

from shared.github_auth import get_github_client
from shared.logger import get_logger

logger = get_logger("step8.pr_creator")


class PRCreator:
    """Creates GitHub Pull Requests with auto-fix changes."""

    def create_pr(
        self,
        repo: str,
        triage: Dict[str, Any],
        plan: Dict[str, Any],
        event_id: str,
        head_branch: str = "",
    ) -> Dict[str, Any]:
        """
        Create a pull request with the proposed fix.

        Args:
            repo: Repository full name (e.g. "user/mlproject")
            triage: Triage result from Step 5
            plan: Fix plan from Step 6
            event_id: Unique event ID
            head_branch: The branch that failed (target for PR)

        Returns:
            PR metadata dict with url, branch, status, etc.
        """
        try:
            g = get_github_client()
            repository = g.get_repo(repo)

            # Determine base branch
            base_branch = head_branch or repository.default_branch

            # Build branch name
            failure_type = triage.get("failure_type", "unknown")
            short_id = event_id.split("-")[-1][:8] if event_id else "fix"
            fix_branch = f"fix/{failure_type}-{short_id}"

            logger.info(
                "creating_pr",
                repo=repo,
                base_branch=base_branch,
                fix_branch=fix_branch,
            )

            # Get the latest commit SHA of the base branch
            base_ref = repository.get_git_ref(f"heads/{base_branch}")
            base_sha = base_ref.object.sha

            # Create the fix branch
            try:
                repository.create_git_ref(
                    ref=f"refs/heads/{fix_branch}",
                    sha=base_sha,
                )
                logger.info("branch_created", branch=fix_branch)
            except Exception as e:
                if "Reference already exists" in str(e):
                    logger.warning("branch_exists", branch=fix_branch)
                else:
                    raise

            # Apply code changes from the plan
            code_changes = plan.get("code_changes", [])
            commit_sha = None

            if code_changes:
                commit_sha = self._apply_changes(
                    repository, fix_branch, code_changes, event_id
                )
            else:
                # If no specific code changes, create a placeholder commit
                # (This happens with template-based plans that need manual detail)
                commit_sha = self._create_placeholder_commit(
                    repository, fix_branch, triage, plan, event_id
                )

            # Build PR title and body
            title = self._build_pr_title(triage, plan)
            body = self._build_pr_body(triage, plan, event_id)

            # Create the Pull Request
            pr = repository.create_pull(
                title=title,
                body=body,
                head=fix_branch,
                base=base_branch,
            )

            # Add label
            try:
                pr.add_to_labels("repomind-auto-fix")
            except Exception:
                pass  # Label might not exist

            result = {
                "url": pr.html_url,
                "number": pr.number,
                "branch": fix_branch,
                "commit_sha": commit_sha or base_sha,
                "title": title,
                "status": "created",
            }

            logger.info("pr_created", pr_url=pr.html_url, pr_number=pr.number)
            return result

        except Exception as e:
            logger.error("pr_creation_failed", repo=repo, error=str(e))
            return {
                "url": None,
                "branch": None,
                "commit_sha": None,
                "title": None,
                "status": "failed",
                "error": str(e),
            }

    def _apply_changes(
        self,
        repository,
        branch: str,
        changes: list,
        event_id: str,
    ) -> Optional[str]:
        """
        Apply code changes to the fix branch.

        Each change can create, modify, or delete a file.
        """
        commit_sha = None

        for change in changes:
            file_path = change.get("file", "")
            action = change.get("action", "modify")
            new_content = change.get("new_content", "")
            description = change.get("description", "Auto-fix")

            if not file_path:
                continue

            try:
                if action == "create":
                    result = repository.create_file(
                        path=file_path,
                        message=f"fix: {description} [{event_id[:20]}]",
                        content=new_content,
                        branch=branch,
                    )
                    commit_sha = result["commit"].sha

                elif action == "modify":
                    # Get current file content
                    file_obj = repository.get_contents(file_path, ref=branch)
                    current_content = file_obj.decoded_content.decode("utf-8")

                    # Apply modification
                    old_content = change.get("old_content", "")
                    if old_content and old_content in current_content:
                        updated = current_content.replace(old_content, new_content, 1)
                    else:
                        updated = new_content

                    result = repository.update_file(
                        path=file_path,
                        message=f"fix: {description} [{event_id[:20]}]",
                        content=updated,
                        sha=file_obj.sha,
                        branch=branch,
                    )
                    commit_sha = result["commit"].sha

                elif action == "delete":
                    file_obj = repository.get_contents(file_path, ref=branch)
                    result = repository.delete_file(
                        path=file_path,
                        message=f"fix: remove {file_path} [{event_id[:20]}]",
                        sha=file_obj.sha,
                        branch=branch,
                    )
                    commit_sha = result["commit"].sha

                logger.info("file_changed", file=file_path, action=action)

            except Exception as e:
                logger.error("file_change_failed", file=file_path, error=str(e))

        return commit_sha

    def _create_placeholder_commit(
        self,
        repository,
        branch: str,
        triage: Dict[str, Any],
        plan: Dict[str, Any],
        event_id: str,
    ) -> Optional[str]:
        """
        Create a placeholder file when no specific code changes are available.
        This ensures the PR has at least one commit diff.
        """
        timestamp = datetime.now(timezone.utc).isoformat()
        content = (
            f"# RepoMind Auto-Fix Report\n\n"
            f"**Event ID:** {event_id}\n"
            f"**Failure Type:** {triage.get('failure_type', 'unknown')}\n"
            f"**Summary:** {triage.get('summary', 'N/A')}\n"
            f"**Confidence:** {triage.get('confidence', 0)}\n"
            f"**Plan:** {plan.get('description', 'N/A')}\n"
            f"**Generated:** {timestamp}\n\n"
            f"## Suggested Actions\n\n"
        )
        for i, action in enumerate(plan.get("actions", []), 1):
            content += f"{i}. {action}\n"

        content += (
            f"\n---\n"
            f"*This file was auto-generated by RepoMind. "
            f"Please apply the suggested fixes and delete this file.*\n"
        )

        try:
            result = repository.create_file(
                path=f".repomind/{event_id[:30]}-fix-report.md",
                message=f"fix: auto-fix report for {triage.get('failure_type', 'unknown')} [{event_id[:20]}]",
                content=content,
                branch=branch,
            )
            return result["commit"].sha
        except Exception as e:
            logger.error("placeholder_commit_failed", error=str(e))
            return None

    def _build_pr_title(self, triage: Dict[str, Any], plan: Dict[str, Any]) -> str:
        """Build a descriptive PR title."""
        failure_type = triage.get("failure_type", "unknown").replace("_", " ")
        description = plan.get("description", f"Fix {failure_type}")
        return f"🤖 [RepoMind] {description}"

    def _build_pr_body(
        self,
        triage: Dict[str, Any],
        plan: Dict[str, Any],
        event_id: str,
    ) -> str:
        """Build a detailed PR body with all context."""
        confidence = triage.get("confidence", 0)
        confidence_bar = "🟢" if confidence >= 0.8 else "🟡" if confidence >= 0.6 else "🔴"

        body = f"""## 🤖 RepoMind Auto-Fix

> This pull request was automatically generated by **RepoMind CI Auto-Fix Agent**.

### 📋 Failure Analysis

| Field | Value |
|-------|-------|
| **Failure Type** | `{triage.get('failure_type', 'unknown')}` |
| **Confidence** | {confidence_bar} {confidence:.0%} |
| **Summary** | {triage.get('summary', 'N/A')} |
| **Affected File** | `{triage.get('affected_file', 'N/A')}` |
| **Event ID** | `{event_id}` |

### 🔧 Fix Applied

**{plan.get('description', 'Auto-fix')}**

"""
        actions = plan.get("actions", [])
        if actions:
            body += "**Steps:**\n"
            for i, action in enumerate(actions, 1):
                body += f"{i}. {action}\n"
            body += "\n"

        files = plan.get("files_to_modify", [])
        if files:
            body += "**Files Modified:**\n"
            for f in files:
                body += f"- `{f}`\n"
            body += "\n"

        body += f"""### ⚠️ Review Required

Please review this PR carefully before merging:
- [ ] Fix is correct and complete
- [ ] No unintended side effects
- [ ] Tests pass

### 🔗 Links
- Event ID: `{event_id}`

---
*Generated by [RepoMind](https://github.com/repomind) CI Auto-Fix Agent*
"""
        return body
