version = 0.1

[default.deploy.parameters]
stack_name = "repomind"
resolve_s3 = true
s3_prefix = "repomind"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "GitHubAppId=\"2948995\" GitHubInstallationId=\"112432727\" PushgatewayUrl=\"\""
image_repositories = []

[default.global.parameters]
region = "ap-south-1"
